### ISSUE TITLE
I get an error.

### ISSUE THREAD

**Issue by kenyonbowers** [js-emulators/desmond#5]
Hello I keep getting this error.
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'B')
    at Object.Module._prepareRomBuffer (desmond.min.js:1:100755)
    at tryLoadROM (desmond.min.js:1:33286)`
I am using unaltered code (other than updating the paths to files) and it's not working.

**Comment by kenyonbowers** [comment]
nvm I got it to work with the firmware.html one
